/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saulr
 */
public class JDOperacion extends javax.swing.JDialog {

    Conexion cx = new Conexion();
    Connection cc = cx.conectar();
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel tx = null;
    /**
     * Creates new form JDOperacion
     */
    public JDOperacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model.addColumn("IdProducto");
        model.addColumn("NombreProducto");
        model.addColumn("Descripcion");
        model.addColumn("FechaCompra");
        model.addColumn("FechaVencimiento");
        model.addColumn("PrecioVenta");
        model.addColumn("PrecioCompra");

        this.tcompra.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfcompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfvencimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpventa = new javax.swing.JTextField();
        txtpcompra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcompra = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnfin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha Compra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));
        getContentPane().add(txtfcompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Vencimiento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));
        getContentPane().add(txtfvencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 140, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio Venta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Precio Compra");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));
        getContentPane().add(txtpventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 130, 40));
        getContentPane().add(txtpcompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 130, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descripcion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        getContentPane().add(txtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 760, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("COMPRA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        tcompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tcompra);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 362, 920, 330));

        btnagregar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/Imagenes/car.png"))); // NOI18N
        btnagregar.setText("Agregar");
        btnagregar.setContentAreaFilled(false);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        btneliminar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/Imagenes/carx.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setContentAreaFilled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        btnfin.setBackground(new java.awt.Color(255, 255, 255));
        btnfin.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnfin.setForeground(new java.awt.Color(255, 255, 255));
        btnfin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/Imagenes/listo.png"))); // NOI18N
        btnfin.setText("Finalizar Compra");
        btnfin.setContentAreaFilled(false);
        btnfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinActionPerformed(evt);
            }
        });
        getContentPane().add(btnfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 250, 70));

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/Imagenes/hacker.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnfinActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from productos where IdProducto='" + txtcodigo.getText() + "'";
            PreparedStatement p = cc.prepareStatement(sql);
            p.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos Eliminados");
            mostrar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btneliminarActionPerformed
    
      public void mostrar() {
        String[] titulos = {"IdProducto","NombreProducto", "Descripcion", "FechaCompra", "FechaVencimiento", "PrecioVenta", "PrecioCompra"};
        String[] re = new String[7];
        String sql = "select*from productos";
        tx = new DefaultTableModel(null, titulos);
        try {          
            Statement st = cc.createStatement();
            ResultSet r = st.executeQuery(sql);
            while (r.next()) {
                re[0] = r.getString("IdProducto");
                re[1] = r.getString("NombreProducto");
                re[2] = r.getString("Descripcion");
                re[3] = r.getString("FechaCompra");
                re[4] = r.getString("FechaVencimiento");
                re[5] = r.getString("PrecioVenta");
                re[6] = r.getString("PrecioCompra");
                tx.addRow(re);
            }
            tcompra.setModel(tx);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Insert into productos values('" + txtcodigo.getText() + "','" + txtnombre.getText() + "','" + txtdes.getText() + "','" + txtfcompra.getText() + "','"
                    + txtfvencimiento.getText() + "','"
                    + txtpventa.getText() + "','"
                    + txtpcompra.getText() + "')";
            PreparedStatement pp = cc.prepareStatement(sql);
            pp.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos insertados");
            mostrar();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        
    }//GEN-LAST:event_btnagregarActionPerformed
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDOperacion dialog = new JDOperacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnfin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tcompra;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtfcompra;
    private javax.swing.JTextField txtfvencimiento;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpcompra;
    private javax.swing.JTextField txtpventa;
    // End of variables declaration//GEN-END:variables
}
